export const DB_ENVS = {
  SHOPS_DATA_MANAGEMENT_DB_SCHEMA: 'SHOPS_DATA_MANAGEMENT_DB_SCHEMA',
  SHOPS_DATA_MANAGEMENT_DB_PORT: 'SHOPS_DATA_MANAGEMENT_DB_PORT',
  SHOPS_DATA_MANAGEMENT_DB_USERNAME: 'SHOPS_DATA_MANAGEMENT_DB_USERNAME',
  SHOPS_DATA_MANAGEMENT_DB_PASSWORD: 'SHOPS_DATA_MANAGEMENT_DB_PASSWORD',
  SHOPS_DATA_MANAGEMENT_DB_DATABASE: 'SHOPS_DATA_MANAGEMENT_DB_DATABASE',
  SHOPS_DATA_MANAGEMENT_DB_HOST: 'SHOPS_DATA_MANAGEMENT_DB_HOST',
  SHOPS_DATA_MANAGEMENT_DB_DIALECT: 'SHOPS_DATA_MANAGEMENT_DB_DIALECT',
};
