#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "### Running pre-commit hook. ###"

echo "Formatting code..."
npm run format || (echo "Formatting failed!" && exit 1)

echo "Linting code..."
npm run lint || (echo "Linting failed!" && exit 1)

echo "Running tests..."
npm test || (echo "Tests failed!" && exit 1)
